package com.jdsu.drivetest.diag;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : diag/include/diag_lsm_dci.h:44</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class diag_pkt_rsp_tracking_tbl extends Structure {
    /**
     * C type : diag_pkt_tracking_info*
     */
    public diag_pkt_tracking_info.ByReference info;
    /**
     * C type : diag_pkt_rsp_tracking_tbl*
     */
    public ByReference prev;
    /**
     * C type : diag_pkt_rsp_tracking_tbl*
     */
    public ByReference next;

    public diag_pkt_rsp_tracking_tbl() {
        super();
    }

    /**
     * @param info C type : diag_pkt_tracking_info*<br>
     * @param prev C type : diag_pkt_rsp_tracking_tbl*<br>
     * @param next C type : diag_pkt_rsp_tracking_tbl*
     */
    public diag_pkt_rsp_tracking_tbl(diag_pkt_tracking_info.ByReference info, ByReference prev, ByReference next) {
        super();
        this.info = info;
        this.prev = prev;
        this.next = next;
    }

    public diag_pkt_rsp_tracking_tbl(Pointer peer) {
        super(peer);
    }

    protected List<?> getFieldOrder() {
        return Arrays.asList("info", "prev", "next");
    }

    public static class ByReference extends diag_pkt_rsp_tracking_tbl implements Structure.ByReference {

    }

    ;

    public static class ByValue extends diag_pkt_rsp_tracking_tbl implements Structure.ByValue {

    }

    ;
}
