package com.jdsu.drivetest.diag;

import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : diag/include/diag_lsm_dci.h:32</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class diag_pkt_tracking_info extends Structure {
    public int uid;
    /**
     * C type : func_ptr_callback*
     */
    public func_ptr_callback func_ptr;
    /**
     * C type : unsigned char*
     */
    public Pointer rsp_ptr;
    public int rsp_len;
    /**
     * C type : void*
     */
    public Pointer data_ptr;

    public diag_pkt_tracking_info() {
        super();
    }

    ;

    /**
     * @param func_ptr C type : func_ptr_callback*<br>
     * @param rsp_ptr  C type : unsigned char*<br>
     * @param data_ptr C type : void*
     */
    public diag_pkt_tracking_info(int uid, func_ptr_callback func_ptr, Pointer rsp_ptr, int rsp_len, Pointer data_ptr) {
        super();
        this.uid = uid;
        this.func_ptr = func_ptr;
        this.rsp_ptr = rsp_ptr;
        this.rsp_len = rsp_len;
        this.data_ptr = data_ptr;
    }

    public diag_pkt_tracking_info(Pointer peer) {
        super(peer);
    }

    protected List<?> getFieldOrder() {
        return Arrays.asList("uid", "func_ptr", "rsp_ptr", "rsp_len", "data_ptr");
    }

    /**
     * <i>native declaration : diag/include/diag_lsm_dci.h:31</i>
     */
    public interface func_ptr_callback extends Callback {
        void apply(Pointer charPtr1, int len, Pointer data_ptr);
    }

    public static class ByReference extends diag_pkt_tracking_info implements Structure.ByReference {

    }

    ;

    public static class ByValue extends diag_pkt_tracking_info implements Structure.ByValue {

    }

    ;
}
