package com.jdsu.drivetest.diag;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * To query health stats per processor<br>
 * <i>native declaration : diag/include/diag_lsm_dci.h:87</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class diag_dci_health_stats_proc extends Structure {
    /**
     * C type : diag_dci_health_stats*
     */
    public diag_dci_health_stats.ByReference health;
    public int proc;

    public diag_dci_health_stats_proc() {
        super();
    }

    /**
     * @param health C type : diag_dci_health_stats*
     */
    public diag_dci_health_stats_proc(diag_dci_health_stats.ByReference health, int proc) {
        super();
        this.health = health;
        this.proc = proc;
    }

    public diag_dci_health_stats_proc(Pointer peer) {
        super(peer);
    }

    protected List<?> getFieldOrder() {
        return Arrays.asList("health", "proc");
    }

    public static class ByReference extends diag_dci_health_stats_proc implements Structure.ByReference {

    }

    ;

    public static class ByValue extends diag_dci_health_stats_proc implements Structure.ByValue {

    }

    ;
}
