package com.jdsu.drivetest.diag;

import com.jdsu.drivetest.diag.DiagLibrary.pthread_mutex_t;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : diag/include/diag_lsm_dci.h:253</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class diag_dci_client_tbl extends Structure {
    /**
     * C type : diag_dci_reg_tbl_t
     */
    public diag_dci_reg_tbl_t client_info;
    /**
     * C type : func_ptr_logs_callback*
     */
    public func_ptr_logs_callback func_ptr_logs;
    /**
     * C type : func_ptr_events_callback*
     */
    public func_ptr_events_callback func_ptr_events;
    public int data_signal_flag;
    public int data_signal_type;
    /**
     * C type : diag_pkt_rsp_tracking_tbl
     */
    public diag_pkt_rsp_tracking_tbl req_tbl_head;
    /**
     * C type : pthread_mutex_t
     */
    public pthread_mutex_t req_tbl_mutex;

    public diag_dci_client_tbl() {
        super();
    }

    ;

    /**
     * @param client_info     C type : diag_dci_reg_tbl_t<br>
     * @param func_ptr_logs   C type : func_ptr_logs_callback*<br>
     * @param func_ptr_events C type : func_ptr_events_callback*<br>
     * @param req_tbl_head    C type : diag_pkt_rsp_tracking_tbl<br>
     * @param req_tbl_mutex   C type : pthread_mutex_t
     */
    public diag_dci_client_tbl(diag_dci_reg_tbl_t client_info, func_ptr_logs_callback func_ptr_logs, func_ptr_events_callback func_ptr_events, int data_signal_flag, int data_signal_type, diag_pkt_rsp_tracking_tbl req_tbl_head, pthread_mutex_t req_tbl_mutex) {
        super();
        this.client_info = client_info;
        this.func_ptr_logs = func_ptr_logs;
        this.func_ptr_events = func_ptr_events;
        this.data_signal_flag = data_signal_flag;
        this.data_signal_type = data_signal_type;
        this.req_tbl_head = req_tbl_head;
        this.req_tbl_mutex = req_tbl_mutex;
    }

    ;

    public diag_dci_client_tbl(Pointer peer) {
        super(peer);
    }

    protected List<?> getFieldOrder() {
        return Arrays.asList("client_info", "func_ptr_logs", "func_ptr_events", "data_signal_flag", "data_signal_type", "req_tbl_head", "req_tbl_mutex");
    }

    /**
     * <i>native declaration : diag/include/diag_lsm_dci.h:251</i>
     */
    public interface func_ptr_logs_callback extends Callback {
        void apply(Pointer charPtr1, int len);
    }

    /**
     * <i>native declaration : diag/include/diag_lsm_dci.h:252</i>
     */
    public interface func_ptr_events_callback extends Callback {
        void apply(Pointer charPtr1, int len);
    }

    public static class ByReference extends diag_dci_client_tbl implements Structure.ByReference {

    }

    ;

    public static class ByValue extends diag_dci_client_tbl implements Structure.ByValue {

    }

    ;
}
