package com.jdsu.drivetest.diag;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * This is used for querying DCI Log<br>
 * or Event Mask<br>
 * <i>native declaration : diag/include/diag_lsm_dci.h:54</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class diag_log_event_stats extends Structure {
    public short code;
    public int is_set;

    public diag_log_event_stats() {
        super();
    }

    public diag_log_event_stats(short code, int is_set) {
        super();
        this.code = code;
        this.is_set = is_set;
    }

    public diag_log_event_stats(Pointer peer) {
        super(peer);
    }

    protected List<?> getFieldOrder() {
        return Arrays.asList("code", "is_set");
    }

    public static class ByReference extends diag_log_event_stats implements Structure.ByReference {

    }

    ;

    public static class ByValue extends diag_log_event_stats implements Structure.ByValue {

    }

    ;
}
